stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  before_script:
    - docker info
    - docker images
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - NAME=golang
    - TAG=1.21-alpine3.18-build-base
    - docker build -t $DOCKER_USERNAME/$NAME:$TAG . --no-cache --progress plain
    - docker images
    - docker tag $CI_REGISTRY_IMAGE/$NAME:$TAG $CI_REGISTRY_IMAGE/$NAME:$TAG-$CI_PIPELINE_ID
    - docker push "$DOCKER_USERNAME/$NAME:$TAG"
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
#  rules:
#    - if: $CI_COMMIT_TAG
